Thu Oct 23 18:14:16 2025

diff --git a/files/system/usr/bin/localdnsctl b/files/system/usr/bin/localdnsctl
--- a/files/system/usr/bin/localdnsctl
+++ b/files/system/usr/bin/localdnsctl
@@ -42,12 +42,17 @@ update_blocklist() {
     rm ${VERBOSE:+-v} -f "${DNSMASQDIR}/domains-blocklist.conf" "${DNSCRYPTDIR}/domains-blocklist.txt"
     cp ${VERBOSE:+-v} -f "${TMPDIR}/${src_file}" "${dst_file}"
     rm -rf "${TMPDIR}"
+    { if [[ ${BACKEND_TYPE} == "dnscrypt" ]]; then
+            ${SYSTEMCTL} restart dnscrypt-proxy.service
+      elif [[ ${BACKEND_TYPE} == "dnsmasq" ]]; then
+            ${SYSTEMCTL} restart dnsmasq.service
+      fi } || die "Failed to restart DNS services"
     log "INFO" "Blocklist update completed successfully"
 }
 
 toggle_localdns() {
     need_root
-    [[ ! -f "/usr/etc/catcat-os/localdns.d/localdns-resolv.conf" ]] && die "localdns-resolv.conf missing"
+    [[ ! -f "/usr/etc/catcat-os/localdns.d/localdns-resolv.conf" ]] && die "localdns-resolv.conf is missing"
 
     SYSTEMCTL="systemctl"
     case "${1}" in
