Fri May 09 01:26:54 2025

diff --git a/files/system/usr/libexec/catcat-flatpak-manager b/files/system/usr/libexec/catcat-flatpak-manager
--- a/files/system/usr/libexec/catcat-flatpak-manager
+++ b/files/system/usr/libexec/catcat-flatpak-manager
@@ -242,7 +242,7 @@ app_specific_perms() {
 
 # perms for gaming apps
 configure_gaming_apps() {
-  echo -e "\nGiving necessary for gaming to: com.usebottles.bottles"
+  echo -e "\nGiving necessary permissions for gaming to: com.usebottles.bottles"
   flatpak override $SCOPE \
     --device={input,dri} \
     --allow={devel,multiarch,per-app-dev-shm} \
@@ -250,7 +250,7 @@ configure_gaming_apps() {
     --env=DXVK_ASYNC=1 \
   com.usebottles.bottles && echo 'Done' || echo 'Error occurred'
 
-  echo -e "\nGiving necessary for gaming to: net.lutris.Lutris"
+  echo -e "\nGiving necessary permissions for gaming to: net.lutris.Lutris"
   flatpak override $SCOPE \
     --device={input,dri,kvm} \
     --allow={devel,multiarch,per-app-dev-shm} \
@@ -258,7 +258,16 @@ configure_gaming_apps() {
     --env=DXVK_ASYNC=1 \
   net.lutris.Lutris && echo 'Done' || echo 'Error occurred'
 
-  echo -e "\nGiving necessary for gaming to: com.heroicgameslauncher.hgl"
+  echo -e "\nGiving necessary permissions for gaming to: com.valvesoftware.Steam"
+  flatpak override $SCOPE \
+    --device={input,dri,kvm} \
+    --allow={devel,multiarch,per-app-dev-shm} \
+    --filesystem=xdg-config/{MangoHud:ro,vkBasalt:ro} \
+    --env=DXVK_ASYNC=1 \
+  com.valvesoftware.Steam && echo 'Done' || echo 'Error occurred'
+
+
+  echo -e "\nGiving necessary permissions for gaming to: com.heroicgameslauncher.hgl"
   flatpak override $SCOPE \
     --device={input,dri} \
     --allow={devel,multiarch,per-app-dev-shm} \
@@ -266,7 +275,7 @@ configure_gaming_apps() {
     --env=DXVK_ASYNC=1 \
   com.heroicgameslauncher.hgl && echo 'Done' || echo 'Error occurred'
 
-  echo -e "\nGiving necessary for gaming to: io.github.ryubing.Ryujinx"
+  echo -e "\nGiving necessary permissions for gaming to: io.github.ryubing.Ryujinx"
   flatpak override $SCOPE \
     --device={input,dri,kvm} \
     --allow={devel,multiarch,per-app-dev-shm} \
@@ -334,7 +343,7 @@ main() {
 }
 
 [[ $# -eq 0 ]] && {
-  grep -q 'devices=.*!all' "/var/lib/flatpak/overrides/global" | grep -q 'devices=.*!kvm' || {
+  grep 'devices=.*!all' "/var/lib/flatpak/overrides/global" | grep 'devices=.*!kvm' || {
     SCOPE="--system"
     remove_filesystem_access
     disable_network
