Wed May 14 13:15:09 2025

diff --git a/files/system/usr/libexec/catcat-flatpak-manager b/files/system/usr/libexec/catcat-flatpak-manager
--- a/files/system/usr/libexec/catcat-flatpak-manager
+++ b/files/system/usr/libexec/catcat-flatpak-manager
@@ -107,39 +107,39 @@ remove_filesystem_access() {
   done
 }
 
-disable_network() {
-  nonet_for_apps=(
-    "app.fotema.Fotema"
-    "com.boxy_svg.BoxySVG"
-    "com.calibre_ebook.calibre"
-    "com.dec05eba.gpu_screen_recorder"
-    "com.github.johnfactotum.Foliate"
-    "com.github.neithern.g4music"
-    "com.github.PintaProject.Pinta"
-    "com.github.rafostar.Clapper"
-    "com.github.tenderowl.frog"
-    "io.github.mrvladus.List"
-    "me.iepure.devtoolbox"
-    "org.gimp.GIMP"
-    "org.gnome.clocks"
-    "org.gnome.World.Iotas"
-    "org.gnome.World.PikaBackup"
-    "org.inkscape.Inkscape"
-    "org.kde.krita"
-    "org.keepassxc.KeePassXC"
-    "org.libreoffice.LibreOffice"
-    "org.onlyoffice.desktopeditors"
-    "org.shotcut.Shotcut"
-    "org.upscayl.Upscayl"
-    "org.videolan.VLC"
-  )
+#disable_network() {
+#  nonet_for_apps=(
+#    "app.fotema.Fotema"
+#    "com.boxy_svg.BoxySVG"
+#    "com.calibre_ebook.calibre"
+#    "com.dec05eba.gpu_screen_recorder"
+#    "com.github.johnfactotum.Foliate"
+#    "com.github.neithern.g4music"
+#    "com.github.PintaProject.Pinta"
+#    "com.github.rafostar.Clapper"
+#    "com.github.tenderowl.frog"
+#    "io.github.mrvladus.List"
+#    "me.iepure.devtoolbox"
+#    "org.gimp.GIMP"
+#    "org.gnome.clocks"
+#    "org.gnome.World.Iotas"
+#    "org.gnome.World.PikaBackup"
+#    "org.inkscape.Inkscape"
+#    "org.kde.krita"
+#    "org.keepassxc.KeePassXC"
+#    "org.libreoffice.LibreOffice"
+#    "org.onlyoffice.desktopeditors"
+#    "org.shotcut.Shotcut"
+#    "org.upscayl.Upscayl"
+#    "org.videolan.VLC"
+#  )
 
-  echo ''
-  for app in "${nonet_for_apps[@]}"; do
-    echo "Remove existing network permissions for app: $app"
-    flatpak override $SCOPE --unshare=network $app && echo 'Done' || echo 'Error occurred'
-  done
-}
+#  echo ''
+#  for app in "${nonet_for_apps[@]}"; do
+#    echo "Remove existing network permissions for app: $app"
+#    flatpak override $SCOPE --unshare=network $app && echo 'Done' || echo 'Error occurred'
+#  done
+#}
 
 # secure flatpak apps
 apply_global_restrictions() {
@@ -310,7 +310,6 @@ main() {
         ;;
       -a|--all)
         remove_filesystem_access
-        disable_network
         apply_global_restrictions
         allow_home
         allow_gpu_acceleration
@@ -345,7 +344,6 @@ main() {
   remove_filesystem_access
   grep 'devices=.*!all' "/var/lib/flatpak/overrides/global" | grep 'devices=.*!kvm' || {
     SCOPE="--system"
-    disable_network
     apply_global_restrictions
   }
 }
