Thu Aug 27 19:44:13 2026

diff --git a/build/builder b/build/builder
--- a/build/builder
+++ b/build/builder
@@ -2,7 +2,7 @@
 set -euo pipefail
 umask 0022
 SCRIPT_DIR="$(cd -- "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
-source "$(dirname ${SCRIPT_DIR})/setup/setup_lib/funcvar.sh"
+source "$(dirname "${SCRIPT_DIR}")/setup/setup_lib/funcvar.sh"
 
 prep_metadata() {
     BUILD_ARGS=(
@@ -24,12 +24,9 @@ prep_metadata() {
     )
 
     BUILD_LABELS=(
-        "--label" "io.artifacthub.package.deprecated=false"
-        "--label" "io.artifacthub.package.prerelease=false"
-        "--label" "io.artifacthub.package.readme-url=${PROJECT_README}"
         "--label" "org.opencontainers.image.documentation=${PROJECT_README}"
         "--label" "org.opencontainers.image.source=${PROJECT_SOURCE}"
-        "--label" "org.opencontainers.image.created=${AH_DATE}"
+        "--label" "org.opencontainers.image.created=${DATETIMESTAMP}"
         "--label" "org.opencontainers.image.description=${PROJECT_DESCRP}"
         "--label" "org.opencontainers.image.title=${IMAGE_NAME}"
         "--label" "org.opencontainers.image.vendor=${PROJECT_VENDOR}"
@@ -50,13 +47,18 @@ sect_border() {
     symmetric_heading "#" "#" "100" "blue" | tr ' ' '#'
 }
 
+# SC2154 - variable is referenced but not assigned.
+# shellcheck disable=SC2154
 build_image() {
     local log_dir="${SCRIPT_DIR}/.log/${IMAGE_NAME}"
     local log_file="${log_dir}/${IMAGE_NAME}.${DATETIMESTAMP}.log"
+    local tag build_tags=()
 
-    [[ ! -d "${log_dir}" ]] && mkdir -p "${log_dir}"
+    for tag in ${BUILD_TAGS}; do
+        build_tags+=("--tag" "${IMAGE_NAME}:${tag}")
+    done
 
-    BUILD_TAGS=($(printf -- "--tag ${IMAGE_NAME}:%s\n" ${BUILD_TAGS}))
+    ensure_dir "${log_dir}"
 
     {
     sect_border
@@ -65,24 +67,33 @@ build_image() {
     echo "${yellow}" " Datestamp     - ${DATETIMESTAMP}${noc}"
     echo "${cyan}"   " Git Commit    - ${COMMIT_SHA}${noc}"
     sect_border
+
     _cmd_test_timer_start=$(date +%s)
-    cd "$(dirname ${SCRIPT_DIR})"
+    cd "$(dirname "${SCRIPT_DIR}")"
     { brief_trace; } 2>/dev/null
     podman build "$@" \
                  --pull=newer \
-                 --secret "id=sbmok_priv,env=SBMOK_KEY" \
+                 --dns 9.9.9.9 \
+                 --secret "id=sbmok_priv,src=${SBMOK_KEY},type=file" \
                  --file "Containerfile" \
                  "${BUILD_LABELS[@]}" \
                  "${BUILD_ARGS[@]}" \
-                 "${BUILD_TAGS[@]}" \
+                 "${build_tags[@]}" \
                  .
     { brief_trace; } 2>/dev/null
+    _cmd_test_timer_end=$(cmd_test_timer)
+
     sect_border
     echo "${green}"  " Build Done    - ${IMAGE_NAME}:${DEFAULT_TAG}${noc}"
-    echo "${purple}" " Build Time    - $(cmd_test_timer)${noc}"
+    echo "${purple}" " Build Time    - ${_cmd_test_timer_end}${noc}"
     sect_border
     } \
-    2>&1 | while read -r line; do echo "$(date +'[%T.%3N]') ${line}"; done \
+    2>&1 | \
+    perl -MTime::HiRes=gettimeofday -ne '
+        $|=1;
+        ($s, $usec) = gettimeofday();
+        ($sec,$min,$hour,$mday,$mon,$year) = localtime($s);
+        printf("[%02d:%02d:%02d.%03d] %s", $hour, $min, $sec, $usec/1000, $_);' \
     2>&1 | tee -a "${log_file}"
 
     ln -sf "${log_file}" "${log_dir}/${IMAGE_NAME}.last.log"
@@ -92,14 +103,15 @@ containerized_rpm_ostree() {
     podman run --rm --privileged \
                -v /var/lib/containers:/var/lib/containers \
                --entrypoint /usr/bin/rpm-ostree \
-               ${BASE_IMAGE}:${MAJOR_VERSION} \
+               "${BASE_IMAGE}:${MAJOR_VERSION}" \
                "$@"
 }
 
 chunk_image() {
     sect_border
-    echo "${green}" " Chunking      - ${IMAGE_NAME}:${DEFAULT_TAG}"
+    echo "${green}" " Chunking       - ${IMAGE_NAME}:${DEFAULT_TAG}${noc}"
     sect_border
+
     _cmd_test_timer_start=$(date +%s)
     { brief_trace; } 2>/dev/null
     ${RPM_OSTREE} compose \
@@ -109,23 +121,26 @@ chunk_image() {
                   --from "localhost/${IMAGE_NAME}:${DEFAULT_TAG}" \
                   --output containers-storage:"localhost/${IMAGE_NAME}-chunked:${DEFAULT_TAG}"
     { brief_trace; } 2>/dev/null
+    _cmd_test_timer_end=$(cmd_test_timer)
+
     sect_border
-    echo "${green}"  " Chunk Done    - ${IMAGE_NAME}:${DEFAULT_TAG}"
-    echo "${purple}" " Chunk Time    - $(cmd_test_timer)"
+    echo "${green}"  " Chunk Done    - ${IMAGE_NAME}:${DEFAULT_TAG}${noc}"
+    echo "${purple}" " Chunk Time    - ${_cmd_test_timer_end}${noc}"
     sect_border
 }
 
 push_image() {
     # Always push image without chunked suffix
-    local push_image="${IMAGE_NAME/-chunked/}" build_tags="${BUILD_TAGS}" tag
+    local push_image="${IMAGE_NAME/-chunked/}" push_tags="${BUILD_TAGS}" tag
     digestfile="/tmp/digestfile"
 
     sect_border
-    echo "${green}"  " Pushing       - ${push_image}:${DEFAULT_TAG}"
-    echo "${purple}" " Push Registry - ${PUSH_REGISTRY}"
+    echo "${green}"  " Pushing       - ${push_image}:${DEFAULT_TAG}${noc}"
+    echo "${purple}" " Push Registry - ${PUSH_REGISTRY}${noc}"
     sect_border
+
     _cmd_test_timer_start=$(date +%s)
-    for tag in ${build_tags}; do
+    for tag in ${push_tags}; do
         log "INFO" "Pushing: ${push_image}:${tag}"
         { brief_trace; } 2>/dev/null
         podman tag "${IMAGE_NAME}:${DEFAULT_TAG}" "${PUSH_REGISTRY}/${push_image}:${tag}"
@@ -134,9 +149,11 @@ push_image() {
         { brief_trace; } 2>/dev/null
         log "INFO" "Pushed: ${push_image}:${tag}"
     done
+    _cmd_test_timer_end=$(cmd_test_timer)
+
     sect_border
-    echo "${green}"  " Push Done    - ${IMAGE_NAME}:${DEFAULT_TAG}"
-    echo "${purple}" " Push Time    - $(cmd_test_timer)"
+    echo "${green}"  " Push Done    - ${IMAGE_NAME}:${DEFAULT_TAG}${noc}"
+    echo "${purple}" " Push Time    - ${_cmd_test_timer_end}${noc}"
     sect_border
 }
 
@@ -167,7 +184,7 @@ gh_hook() {
         case "${cmd}" in
             pre-build)
                 # Add build tags
-                BUILD_TAGS="${BUILD_TAGS} ${EXTRA_TAGS[@]}"
+                BUILD_TAGS="${BUILD_TAGS} ${EXTRA_TAGS[*]}"
                 echo "build_tags=${BUILD_TAGS}" >> "${GITHUB_OUTPUT}"
                 # Add real image_name
                 echo "image_name=${IMAGE_NAME}" >> "${GITHUB_ENV}"
@@ -178,7 +195,7 @@ gh_hook() {
                 ;;
             post-push)
                 # Add digestfile for cosign
-                echo "digest=$(< ${digestfile})" >> "${GITHUB_OUTPUT}"
+                echo "digest=$(< "${digestfile}")" >> "${GITHUB_OUTPUT}"
                 unset digestfile
                 ;;
             *)
@@ -211,10 +228,13 @@ main() {
             -h|--help)
                 show_help;          exit  0 ;;
             -i|--image-name)
+                [[ -n "${2:-}" ]] || die "Provide image name"
                 IMAGE_NAME="${2}";  shift 2 ;;
             -b|--base-image)
+                [[ -n "${2:-}" ]] || die "Provide base image"
                 BASE_IMAGE="${2}";  shift 2 ;;
             -t|--alt-tag)
+                [[ -n "${2:-}" ]] || die "Provide alt tag"
                 ALT_TAG="${2}";     shift 2 ;;
             *)
                 rem_args+=("${1}"); shift   ;;
@@ -222,9 +242,9 @@ main() {
     done
 
     RPM_OSTREE="$(command -v rpm-ostree)" || true
-    if [[ -z "${RPM_OSTREE:-}" ]]; then
-        [[ $(id -u) -ne 0 ]] &&
-            die "Require root privileges, rpm-ostree command does not exists on current system"
+    if [[ ! -x "${RPM_OSTREE:-}" ]]; then
+        [[ ${EUID} -ne 0 ]] &&
+            die "Requires root privileges, rpm-ostree command not found on current system"
         RPM_OSTREE="containerized_rpm_ostree"
     fi
 
@@ -243,11 +263,8 @@ main() {
                 ;;
             *)
                 # Collect args for active subcommand
-                if [[ -n "${curr_cmd:-}" ]]; then
-                    curr_args+=("${arg}")
-                else
-                    die "Non glabl flag '${arg}' provided before subcommand"
-                fi
+                { [[ -n "${curr_cmd:-}" ]] && curr_args+=("${arg}"); } ||
+                die "Non glabl flag '${arg}' provided before subcommand"
                 ;;
         esac
     done
diff --git a/files/system/usr/bin/buttercare b/files/system/usr/bin/buttercare
--- a/files/system/usr/bin/buttercare
+++ b/files/system/usr/bin/buttercare
@@ -13,10 +13,10 @@ show_btrfs_usage() {
     local path="${1}"
     validate_path "btrfs" "${path}"
     log "INFO" "Showing BTRFS detailed usage for ${path}"
-    ${BTRFS} filesystem usage "${path}"
+    "${BTRFS[@]}" filesystem usage "${path}"
     echo
     log "INFO" "Showing BTRFS disk space for ${path}"
-    ${BTRFS} filesystem df "${path}"
+    "${BTRFS[@]}" filesystem df "${path}"
 }
 
 # Perform balance operation
@@ -35,22 +35,23 @@ balance() {
     local mounts=("${path}")
     if [[ "${path}" == "all" ]]; then
         log "INFO" "Auto detecting BTRFS mount points"
-        mounts=($(get_btrfs_mounts))
-        log "INFO" "Mount points detected: ${mounts[@]}"
+        mounts=()
+        readarray -t mounts < <(get_btrfs_mounts)
+        log "INFO" "Mount points detected: ${mounts[*]}"
     fi
 
     btrfs_df() {
         log "INFO" "${1} disk space usage (btrfs filesystem df):"
-        ${BTRFS} filesystem df "${_mount}"
+        "${BTRFS[@]}" filesystem df "${_mount}"
     }
 
     local _mount
-    for _mount in ${mounts[@]}; do
+    for _mount in "${mounts[@]}"; do
         validate_path "btrfs" "${_mount}"
         log "INFO" "Starting balance on ${_mount}"
         [[ -n ${VERBOSE} ]] && btrfs_df "Pre-balance"
         echo ""
-        ${BTRFS} balance start -musage="${musage}" -dusage="${dusage}" --enqueue "${_mount}"
+        "${BTRFS[@]}" balance start -musage="${musage}" -dusage="${dusage}" --enqueue "${_mount}"
         echo ""
         [[ -n ${VERBOSE} ]] && btrfs_df "Post-balance"
         log "INFO" "Balance completed for ${_mount}"
@@ -74,7 +75,7 @@ defrag() {
     validate_path "btrfs" "${path}"
 
     log "INFO" "Starting defragmentation on ${path} (compression: ${comp}${level:+, level: ${level}})"
-    ${BTRFS} filesystem defragment -r -c"${comp}" ${level:+-L ${level}} "${path}"
+    "${BTRFS[@]}" filesystem defragment -r -c"${comp}" ${level:+-L ${level}} "${path}"
     log "INFO" "Defragmentation completed for ${path}"
 }
 
@@ -83,7 +84,7 @@ scrub() {
     local path="${1}"
     validate_path "btrfs" "${path}"
     log "INFO" "Starting scrub on ${path}"
-    ${BTRFS} scrub start -B "${path}"
+    "${BTRFS[@]}" scrub start -B "${path}"
     log "INFO" "Scrub completed for ${path}"
 }
 
@@ -92,62 +93,76 @@ scrub() {
 trim() {
     local path="${1:-}"
     if [[ -z "${path}" ]]; then
-        log "INFO" "Running TRIM on fstab entries"
-        ${FSTRIM} --fstab
-        log "INFO" "TRIM completed on fstab entries"
+        log "INFO" "Running TRIM on: fstab entries"
+        "${FSTRIM[@]}" --fstab
+        log "INFO" "TRIM completed on: fstab entries"
     else
-        log "INFO" "Running TRIM on ${path}"
-        ${FSTRIM} "${path}"
-        log "INFO" "TRIM completed on ${path}"
+        log "INFO" "Running TRIM on: ${path}"
+        "${FSTRIM[@]}" "${path}"
+        log "INFO" "TRIM completed on: ${path}"
     fi
 }
 
 show_help() {
     cat <<EOF
-Usage: $(basename "${0}") [global_options] command1 [options] [command2 [options] ..."
+Usage: $(basename "${0}") [global_options] command1 [options] [command2] [options] ..."
 
 Global Options:
   -h, --help              Show this help message
-  -v, --verbose           Enable verbose output (use -vv for debug verbosity)
+  -v, --verbose           Enable verbose output (use -vv for debug mode)
 
 Commands:
-  usage  <path>           Show BTRFS filesystem usage and disk space information
+  usage <path>            Show BTRFS filesystem usage and disk space information
 
-  balance                 Start balance operation on BTRFS filesystem
-                          Note: Balance operation auto detects all BTRFS mount points if no path specified
-                          Options: -m [musage] -d [dusage] -p [path|all] (Defaults: musage=50, dusage=80, path=all)
+  balance [path]          Start balance operation on BTRFS filesystem
+                          Options: -m [musage] -d [dusage] -p [path|all]
+                          (Defaults: musage=50, dusage=80, path=all)
 
   defrag                  Defragment the BTRFS filesystem using a specified compression algorithm
                           Options: -c <algorithm> -l [level] -p <path>
 
-  scrub  <path>           Start a scrub operation on BTRFS filesystem
+  scrub <path>            Start a scrub operation on BTRFS filesystem
 
-  trim   [path]           Perform TRIM operation on the path
-                          Note: TRIM operation uses fstab entries if no path specified
+  trim [path]             Perform TRIM operation on the path
+
+Notes:
+  * Balance operation auto detects all BTRFS mount points if no path specified.
+
+  * TRIM operation uses fstab entries if no path specified.
+
 EOF
 }
 
 exec_subcommand() {
-    need_root
-    BTRFS="$(echo 'btrfs' ${VERBOSE:+-v})"
-    FSTRIM="$(echo 'fstrim' ${VERBOSE:+-v})"
     local cmd="${1}"; shift
+    BTRFS=("btrfs")
+    FSTRIM=("fstrim")
+    [[ -n "${VERBOSE:-}" ]] && {
+        BTRFS+=("-v")
+        FSTRIM+=("-v")
+    }
+
+    need_root
     case "${cmd}" in
-        usage) [[ $# -eq 1 ]] && show_btrfs_usage "${1}" ||
-                   die "BTRFS mount path required to show usage"
+        usage)
+            [[ -n "${1:-}" ]] || die "BTRFS mount path required to show usage"
+            show_btrfs_usage "${1}"
             ;;
-        defrag) defrag "$@"
+        defrag)
+            [[ -n "${*:-}" ]] || die "Provide defrag options"
+            defrag "$@"
             ;;
-        balance) balance "$@"
+        balance)
+            balance "$@"
             ;;
-        scrub) [[ $# -eq 1 ]] && scrub "${1}" ||
-                   die "BTRFS mount path required for scrub"
+        scrub)
+            [[ -n "${1:-}" ]] || die "BTRFS mount path required for scrub"
+            scrub "${1}"
             ;;
-        trim) [[ $# -le 1 ]] && trim  "$@" ||
-                  die "Usage: $(basename ${0}) trim [PATH]"
+        trim)
+            trim  "$@"
             ;;
-        *) die "Unknown command: ${cmd}" show_help
-            ;;
+        *) die "Unknown command: ${cmd}" show_help ;;
     esac
 }
 
@@ -164,7 +179,7 @@ main() {
             -v|--verbose)
                 VERBOSE=1;          shift ;;
             -vv)
-                VERBOSE=2;          shift ;;
+                VERBOSE=3;          shift ;;
             *)
                 rem_args+=("${1}"); shift ;;
         esac
@@ -183,11 +198,8 @@ main() {
                 ;;
             *)
                 # Collect args for active subcommand
-                if [[ -n "${curr_cmd:-}" ]]; then
-                    curr_args+=("${arg}")
-                else
-                    die "Non glabl flag '${arg}' provided before subcommand"
-                fi
+                { [[ -n "${curr_cmd:-}" ]] && curr_args+=("${arg}"); } ||
+                die "Non glabl flag '${arg}' provided before subcommand"
                 ;;
         esac
     done
diff --git a/files/system/usr/libexec/catcat-user-setup b/files/system/usr/libexec/catcat-user-setup
--- a/files/system/usr/libexec/catcat-user-setup
+++ b/files/system/usr/libexec/catcat-user-setup
@@ -1,5 +1,4 @@
 #!/usr/bin/bash
-shopt -s extglob nocasematch
 source /usr/lib/catcat-os/funcvar.sh
 exit_if_root
 HOME_DIR="${HOME}"
@@ -12,9 +11,7 @@ on_first_boot() {
     local firstboot_file="${CATCAT_CONFD}/log/.first-boot-done"
     if [[ ! -f "${firstboot_file}" ]]; then
         FIRSTBOOT=true
-        mkdir -pv "$(dirname ${firstboot_file})"
-        systemctl is-active gdm &&
-            dconf reset -f /org/gnome/Ptyxis
+        mkdir -pv "$(dirname "${firstboot_file}")"
         echo 'first boot' > "${firstboot_file}"
     fi
 }
@@ -27,7 +24,7 @@ sync_default_configs() {
     log "INFO" "Updating configs..."
     if ! diff -q "${update_info}" "${lastup_info}" >/dev/null 2>&1; then
         CATCAT_SYSTEM_UPDATED=true
-        mkdir -pv "${CATCAT_CONFD}"/{log,LS_COLORS_DIR}
+        ensure_dir "${CATCAT_CONFD}"/{log,LS_COLORS_DIR}
         cp -vf /usr/share/catcat-os/LS_COLORS_DIR/* "${CATCAT_CONFD}/LS_COLORS_DIR"/
 
         rsync -aK --ignore-existing --exclude='*.gitkeep*' "${SKEL}"/ "${HOME_DIR}"/ ||
@@ -42,6 +39,7 @@ sync_default_configs() {
             systemctl is-active gdm &&
                 rsync -au "${SKEL}/.local/share/gnome-shell/extensions" "${LOCALSHARE}/gnome-shell"/
 
+            # TODO: replace with ocopy
             { rm -rf "${LOCALSHARE}/themes"/*{Catppuccin,Lavanda}*
               cp -drf /usr/share/themes/*{Catppuccin,Lavanda}* "${LOCALSHARE}/themes"/; } ||
                 err "Theme update failed"
@@ -56,41 +54,21 @@ gnome_shell_setup() {
     log "INFO" "Setting up GNOME Shell..."
 
     # Disable extension update if there are no updates in extension update directory
-    local ext_updates="${LOCALSHARE}/gnome-shell/extension-updates"
-    [[ ! -d "${ext_updates}" ]] && mkdir -pv "${ext_updates}"
-    local octalmode=$( [[ $(ls -A1 "${ext_updates}" | wc -l) -eq 0 ]] && echo "544" || echo "755" )
-    chmod ${octalmode} "${ext_updates}" &&
+    local octalmode="544" ext_updates="${LOCALSHARE}/gnome-shell/extension-updates"
+
+
+    ensure_dir "${ext_updates}"
+    if [[ -n "$(find "${ext_updates}" -mindepth 1 -maxdepth 1 -print -quit)" ]]; then
+        octalmode="755"
+    fi
+    chmod -v "${octalmode}" "${ext_updates}" &&
         log "INFO" "Extensions update directory octal permission set to ${octalmode}"
-
-    # Syncthing style
-    if [[ -n ${CATCAT_DESKTOP_UPDATED} ]]; then
-        sed -i 's|#FFFFFF|#cdd6f4|;s|#ffffff|#cdd6f4|' \
-            "${LOCALSHARE}/gnome-shell/extensions/syncthing@gnome.2nv2u.com/icons"/*.svg ||
-                err "Syncthing style setup failed"
-    fi
-
-    # Setup burn-my-windows
-    local bmw_profile="${CONFIG}/burn-my-windows/profiles/1679372508290696.conf"
-    if [[ ! -f "${bmw_profile}" ]]; then
-        bak_before "${CONFIG}/burn-my-windows"
-        cp -drvf "${SKEL}/.config/burn-my-windows" "${CONFIG}"/ &&
-        dconf write /org/gnome/shell/extensions/burn-my-windows/active-profile "'${bmw_profile}'" ||
-            err "Burn my windows style setup failed"
-    fi
-
-    # Setup forge auto tilling
-    local forge_stylesheet="forge/stylesheet/forge/stylesheet.css"
-    if [[ $(grep -c 'border-width: 1px' "${CONFIG}/${forge_stylesheet}") -lt 6 ]]; then
-        bak_before "${CONFIG}/forge"
-        cp -drvf "${SKEL}/.config/${forge_stylesheet}" "${CONFIG}/${forge_stylesheet}" ||
-            err "Forge style setup failed"
-    fi
 
     # Gnome for Handheld
     if command -v hhdctl; then
         [[ "${ENABLED_GNOME_EXTENSIONS}" =~ "gjsosk@vishram1123.com" ]] ||
             gnome-extensions enable gjsosk@vishram1123.com
-        [[ -n ${FIRSTBOOT} ]] &&
+        [[ -n ${FIRSTBOOT:-} ]] &&
             dconf write /org/gnome/desktop/interface/text-scaling-factor "1.2"
     fi
 
@@ -127,7 +105,7 @@ set_folder_icons() {
         )
         local _dir
         for _dir in "${!icons[@]}"; do
-            [[ ! -d "${HOME_DIR}/${_dir}" ]] && mkdir -pv "${HOME_DIR}/${_dir}"
+            ensure_dir "${HOME_DIR}/${_dir}"
             { gio set "${HOME_DIR}/${_dir}" metadata::custom-icon-name "${icons[${_dir}]}" &&
                 log "INFO" "Folder icon '${icons[${_dir}]}' set to ${HOME_DIR}/${_dir}"
             } || err "Failed to set Folder icon '${icons[${_dir}]}' to ${HOME_DIR}/${_dir}"
@@ -148,13 +126,13 @@ setup_bookmarks_userdirs() {
                 err "Failed to set default user directories"
     fi
 
-    mkdir -pv "/tmp/tmp-${USER}"
+    ensure_dir "/tmp/tmp-${USER}"
     if systemctl is-active gdm; then
         if ! grep "admin:/// AdminRoot" "${bookmarks}"; then
         log "INFO" "Adding Bookmarks"
+        ensure_dir "$(dirname "${bookmarks}")"
         bak_before "${bookmarks}"
-        mkdir -pv "$(dirname "${bookmarks}")" &&
-        sh -c "echo 'file:///home/${USER}/Me Me
+        echo "file:///home/${USER}/Me Me
 file:///home/${USER}/Me/Documents Documents
 file:///home/${USER}/Me/Downloads Downloads
 file:///home/${USER}/Me/Pictures Pictures
@@ -162,7 +140,7 @@ file:///home/${USER}/Me/Videos Videos
 file:///home/${USER}/Me/Music Music
 file:///home/${USER}/Me/Notes Notes
 admin:/// AdminRoot
-file:///tmp/tmp-${USER} Temporary' > ${bookmarks}" || err "Failed to add bookmarks"
+file:///tmp/tmp-${USER} Temporary" > "${bookmarks}" || err "Failed to add bookmarks"
         fi
     fi
 }
@@ -191,9 +169,6 @@ remove_unnecessary_directories() {
 
     [[ -f "${HOME_DIR}/Me/Desktop/.gitkeep" ]] &&
         find "${HOME_DIR}/Me" -maxdepth 2 -mindepth 1 -type f -name '*.gitkeep' -print -delete
-
-    [[ -d "${HOME_DIR}/Sync" && $(ls -A1 "${HOME_DIR}/Sync" | wc -l) -lt 2 ]] &&
-        rm -rvf "${HOME_DIR}/Sync"
     log "INFO" "Done"
 }
 
@@ -201,24 +176,17 @@ remove_unnecessary_directories() {
 
 shell_setup() {
     log "INFO" "Setting up shell..."
-    #/usr/bin/bat cache --build # is in profile.d
+    # Build bat cache
+    /usr/bin/bat cache --build
 
     # Fish shell
     # To load fish config
     sed '/status is-interactive || exit 0/d' \
             /usr/share/fish/vendor_conf.d/a-decor.fish | fish >/dev/null
     #
-    if [[ -n ${CATCAT_SYSTEM_UPDATED} ]]; then
-        [[ ! -d "${CONFIG}/fish/themes" ]] && mkdir -vp "${CONFIG}/fish/themes"
+    if [[ -n ${CATCAT_SYSTEM_UPDATED:-} ]]; then
+        ensure_dir "${CONFIG}/fish/themes"
     fi
-
-    local shell_rc='
-[[ -d ~/.shell.d ]] && for rc in ~/.shell.d/*; do [[ -f "${rc}" ]] && . "${rc}"; done
-unset rc'
-    grep -q "\.shell\.d" "${HOME_DIR}/.bashrc" || echo "${shell_rc}" >> "${HOME_DIR}/.bashrc"
-
-    grep -q "\[ -f ~/\.bashrc \]" "${HOME_DIR}/.bash_profile" ||
-        echo "[[ -f ~/.bashrc ]] && . ~/.bashrc" >> "${HOME_DIR}/.bash_profile"
 
     log "INFO" "Done"
 }
@@ -228,19 +196,21 @@ unset rc'
 theme_flatpak_apps() {
     log "INFO" "Setting theme, icons and permissions for flatpak apps..."
 
-    if ! grep 'devices=.*!all' "${LOCALSHARE}/flatpak/overrides/global" | grep 'devices=.*!kvm'; then
-        [[ ! -d "${LOCALSHARE}/flatpak/overrides" ]] &&
-            mkdir -vp "${LOCALSHARE}/flatpak/overrides"
+    local floverrides_global="${LOCALSHARE}/flatpak/overrides/global"
 
-        [[ -f "${LOCALSHARE}/flatpak/overrides/global" ]] &&
-            bak_before "${LOCALSHARE}/flatpak/overrides/global"
+    ensure_dir "$(direname "${floverrides_global}")"
+    ensure_file "${floverrides_global}"
+
+    if ! grep 'devices=.*!all' "${floverrides_global}" | grep 'devices=.*!kvm'; then
+        [[ -f "${floverrides_global}" ]] &&
+            bak_before "${floverrides_global}"
 
         /usr/libexec/catcat-flatpak-manager --user --all ||
             err "Failed to configure flatpak permissions"
     fi
 
     if [[ ! "$(ls -Al "${HOME_DIR}/.themes" )"  =~ '.local/share/themes' ]]; then
-        mkdir -pv "${LOCALSHARE}"/{themes,icons,fonts}
+        ensure_dir "${LOCALSHARE}"/{themes,icons,fonts}
         local _dir
         for _dir in themes icons; do
             [[ -d "${HOME_DIR}/.${_dir}" ]] &&
@@ -249,7 +219,7 @@ theme_flatpak_apps() {
             ln -srfTv "${LOCALSHARE}/${_dir}" "${HOME_DIR}/.${_dir}"
         done
 
-        [[ $(ls -A1 "${CONFIG}/gtk-4.0" | wc -l) -eq 0 ]] &&
+        [[ -d "${CONFIG}/gtk-4.0" && -n "$(ls -A "${CONFIG}/gtk-4.0")" ]] ||
             cp -drvf "${SKEL}/.config/gtk-4.0" "${CONFIG}"/
     fi
     log "INFO" "Done"
@@ -261,15 +231,7 @@ setup_apps() {
     log "INFO" "Configuring apps and desktop files..."
 
     local apps_dir="${LOCALSHARE}/applications"
-    mkdir -pv "${apps_dir}"
-
-    # Handle desktop entries
-    # Prioritize flatpak steam
-    if [[ ! -f "${apps_dir}/steam.desktop" || ! -s "${apps_dir}/steam.desktop" ]]; then
-        command -v steam && [[ "${FLATPAK_APPS}" =~ 'steam' ]] &&
-            sed "/\[Desktop Entry\]/a NoDisplay=true" /usr/share/applications/steam.desktop > \
-                    "${apps_dir}/steam.desktop"
-    fi
+    ensure_dir "${apps_dir}"
 
     # Modify app icons
     local -A app_icons=(
@@ -282,7 +244,7 @@ setup_apps() {
     local _app
     for _app in "${!app_icons[@]}"; do
         if [[ ! -f "${apps_dir}/${_app}.desktop" || ! -s "${apps_dir}/${_app}.desktop" ]]; then
-            [[ "${FLATPAK_APPS}" =~ "${_app}" ]] &&
+            [[ " ${FLATPAK_APPS[*]} " =~ " ${_app} " ]] &&
                 sed "s|^Icon=.*|Icon=${app_icons[${_app}]}|" \
                     "/var/lib/flatpak/exports/share/applications/${_app}.desktop" > \
                         "${apps_dir}/${_app}.desktop"
@@ -297,17 +259,20 @@ setup_apps() {
 
     local gedit_catppuccin="${HOME_DIR}/.var/app/org.gnome.gedit/data/libgedit-gtksourceview-300/styles/catppuccin-mocha.xml"
     [[ ! -f "${gedit_catppuccin}" ]] && {
-        cp -drvf "${SKEL}/.var/app/org.gnome.gedit" "${HOME_DIR}/.var/app/" ||
+        cp -drvf "${SKEL}/.var/app/org.gnome.gedit" "${HOME_DIR}/.var/app"/ ||
             err "Failed to configure Gedit"
     }
 
     # VSCodium extensions
     local vs_extdir="${HOME_DIR}/.vscode-oss/extensions"
-    mkdir -pv "${vs_extdir}"
-    ls -A1d "${vs_extdir}"/*atppuccin* || {
-        cp -drf "${SKEL}/.vscode-oss/extensions"/* "${vs_extdir}"/
-        cp -drf "${SKEL}/.config/VSCodium" "${CONFIG}"/ || err "Failed to configure VSCodium"
-    }
+    ensure_dir "${vs_extdir}"
+    if [[ -d "${SKEL}/.vscode-oss" ]]; then
+        ls -A1d "${vs_extdir}"/*atppuccin* || {
+            cp -drf "${SKEL}/.vscode-oss/extensions"/* "${vs_extdir}"/
+        }
+    fi
+
+    [[ ! -d "${CONFIG}/VSCodium" ]] && cp -drf "${SKEL}/.config/VSCodium" "${CONFIG}"/
 
     log "INFO" "Done"
 }
@@ -320,7 +285,12 @@ main() {
     remove_unnecessary_directories
     setup_bookmarks_userdirs
     if systemctl is-active display-manager; then
-        FLATPAK_APPS="$(ls -A1 /var/lib/flatpak/app/ ${LOCALSHARE}/flatpak/app/)"
+        FLATPAK_PATHS=(
+            "/var/lib/flatpak/app"
+            "${LOCALSHARE}/flatpak/app"
+        )
+        readarray -t FLATPAK_APPS < \
+                    <(find "${FLATPAK_PATHS[@]}" -maxdepth 1 -mindepth 1 -type d -printf "%f\n")
         if systemctl is-active gdm; then
             ENABLED_GNOME_EXTENSIONS="$(dconf read /org/gnome/shell/enabled-extensions)"
             set_folder_icons
