Thu Sep 24 19:30:24 2026

diff --git a/build/builder b/build/builder
--- a/build/builder
+++ b/build/builder
@@ -163,7 +163,7 @@ push_image() {
 
 cosign_image() {
     local digest="$(< "/tmp/${IMAGE_NAME}-digestfile")"
-    [[ -n "$(command -v cosign") ]] || die "Failed, cosign command not found on current system"
+    [[ -n "$(command -v cosign)" ]] || die "Failed, cosign command not found on current system"
 
     sect_border
     echo "${green}"  " Signing OCI   - ${IMAGE_NAME}:${DEFAULT_TAG}${noc}"
