Thu Sep 24 19:22:46 2026

diff --git a/.github/workflows/build-image.yaml b/.github/workflows/build-image.yaml
--- a/.github/workflows/build-image.yaml
+++ b/.github/workflows/build-image.yaml
@@ -1,36 +1,39 @@
 name: Build Images
 on:
   workflow_call:
-    inputs:
-      image_name:
-        required: false
-        type: string
-        default: catcat-os
-      base_image:
-        required: false
-        type: string
-        default: quay.io/fedora-ostree-desktops/silverblue
-      alt_tag:
-        required: false
-        type: string
-        default: main
+  schedule:
+    - cron: "00 6 * * *"    # build at 6:00 UTC every day
+  workflow_dispatch:        # Allows manual trigger of workflow
 
 jobs:
   build_image:
-    name: ${{ inputs.image_name }}
+    name: Build
     runs-on: ubuntu-latest
-    if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
+    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
     permissions:
       contents: read
       packages: write
       id-token: write
+    strategy:
+      fail-fast: false      # Other builds even if one fails
+      matrix:
+        include:
+          - image_name: catcat-os
+            base_image: quay.io/fedora-ostree-desktops/silverblue
+            img_flavor: main
+          - image_name: catcat-os-nv
+            base_image: quay.io/fedora-ostree-desktops/silverblue
+            img_flavor: nvidia
+          - image_name: catcat-os-hh
+            base_image: quay.io/fedora-ostree-desktops/silverblue
+            img_flavor: deck
 
     steps:
       - name: Checkout Repo
         uses: actions/checkout@v7
         with:
           persist-credentials: false
-          fetch-depth: 0
+          fetch-depth: 1
 
       - name: Maximize Build Space
         uses: hastd/free-disk-space@v0.1.2
@@ -41,10 +44,14 @@ jobs:
         shell: bash
         run: |
           sudo truncate -s 70G /mnt/podman-storage.img
-          sudo mkfs.btrfs -f /mnt/podman-storage.img
+          sudo mkfs.btrfs -f -m single -d single /mnt/podman-storage.img
           sudo podman system reset --force
           sudo systemctl stop podman.service
-          sudo mount -o compress-force=zstd:2 /mnt/podman-storage.img /var/lib/containers
+          LOOP=$(sudo losetup --find --show --direct-io=on /mnt/podman-storage.img)
+          sudo mkdir -p /mnt/podman-storage
+          sudo mount -o compress-force=zstd:2,discard=async,noatime "${LOOP}" /mnt/podman-storage
+          sudo mkdir -p /mnt/podman-storage/{storage,tmp}
+          sudo mount --bind /mnt/podman-storage/storage /var/lib/containers/storage
           sudo systemctl start podman.service
 
       - name: Prepare Environment
@@ -58,36 +65,33 @@ jobs:
           nproc --all
           pwd
           ls -A1
-          printf '#!/bin/bash\nsudo -E "${GITHUB_WORKSPACE}/build/builder" "$@"\n' | \
-              install -m 755 -D /dev/stdin "${GITHUB_WORKSPACE}/bin/builder"
-          ln -sv "${GITHUB_WORKSPACE}/build/ENVAR" "${GITHUB_WORKSPACE}/bin"/
-          echo "${GITHUB_WORKSPACE}/bin" >> "${GITHUB_PATH}"
 
       - name: Build Image
         id: build-image
         env:
           SBMOK_KEY: ${{ secrets.SBMOK_KEY }}
+          IMAGE_NAME: ${{ matrix.image_name }}
+          BASE_IMAGE: ${{ matrix.base_image }}
+          IMG_FLAVOR: ${{ matrix.img_flavor }}
         shell: bash
         run: |
           set -euo pipefail
-          source ENVAR
-          builder build \
-                  --image-name "${{ inputs.image_name }}" \
-                  --base-image "${{ inputs.base_image }}" \
-                  --alt-tag    "${{ inputs.alt_tag }}"
+          source "${GITHUB_WORKSPACE}/build/ENVAR"
+          sudo -E "${GITHUB_WORKSPACE}/build/builder \
+                build --image-name "${IMAGE_NAME}" \
+                      --base-image "${BASE_IMAGE}" \
+                      --img-flavor "${IMG_FLAVOR}"
 
       - name: Chunk Image
         id: chunk-image
         env:
-          SBMOK_KEY: ${{ secrets.SBMOK_KEY }}
+          IMAGE_NAME: ${{ matrix.image_name }}
         shell: bash
         run: |
           set -euo pipefail
-          source ENVAR
-          builder chunk \
-                  --image-name "${{ env.image_name }}" \
-                  --base-image "${{ inputs.base_image }}" \
-                  --alt-tag    "${{ inputs.alt_tag }}"
+          source "${GITHUB_WORKSPACE}/build/ENVAR"
+          sudo -E "${GITHUB_WORKSPACE}/build/builder \
+                chunk --image-name "${IMAGE_NAME}"
 
       - name: Login to GitHub Container Registry
         uses: docker/login-action@v4.6.0
@@ -100,15 +104,16 @@ jobs:
         id: push-image
         env:
           build_tags: ${{ steps.build-image.outputs.build_tags }}
+          IMAGE_NAME: ${{ matrix.image_name }}
+          IMG_FLAVOR: ${{ matrix.img_flavor }}
         shell: bash
         run: |
           set -euo pipefail
-          source ENVAR
+          source "${GITHUB_WORKSPACE}/build/ENVAR"
           declare -x BUILD_TAGS="${build_tags}"
-          builder push \
-                  --image-name "${{ env.image_name }}" \
-                  --base-image "${{ inputs.base_image }}" \
-                  --alt-tag    "${{ inputs.alt_tag }}"
+          sudo -E "${GITHUB_WORKSPACE}/build/builder \
+                push --image-name "${IMAGE_NAME}" \
+                     --img-flavor "${IMG_FLAVOR}"
 
       - name: Install Cosign
         uses: sigstore/cosign-installer@v4.1.2
@@ -117,11 +122,11 @@ jobs:
 
       - name: Sign Container Image
         env:
-          IMAGE_FULL: ${{ env.PUSH_REGISTRY }}/${{ inputs.image_name }}
-          DIGEST: ${{ steps.push-image.outputs.digest }}
-          COSIGN_EXPERIMENTAL: false
           COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}
+          IMAGE_NAME: ${{ matrix.image_name }}
         shell: bash
         run: |
-          echo "Image Digest: ${DIGEST}"
-          cosign sign -y --key env://COSIGN_PRIVATE_KEY ${IMAGE_FULL}@${DIGEST}
+          set -euo pipefail
+          source "${GITHUB_WORKSPACE}/build/ENVAR"
+          sudo -E "${GITHUB_WORKSPACE}/build/builder \
+                cosign --image-name "${IMAGE_NAME}"
diff --git a/build/builder b/build/builder
--- a/build/builder
+++ b/build/builder
@@ -2,7 +2,7 @@
 set -euo pipefail
 umask 0022
 SCRIPT_DIR="$(cd -- "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
-source "$(dirname "${SCRIPT_DIR}")/setup/setup_lib/funcvar.sh"
+source "$(dirname "${SCRIPT_DIR}")/setup/lib/bash-lib.sh"
 
 prep_metadata() {
     BUILD_ARGS=(
@@ -19,8 +19,8 @@ prep_metadata() {
         "--build-arg" "TIMESTAMP=${TIMESTAMP}"
         "--build-arg" "COMMIT_SHA=${COMMIT_SHA}"
         "--build-arg" "IMAGE_NAME=${IMAGE_NAME}"
-        "--build-arg" "BASE_IMAGE=${BASE_IMAGE}"
-        "--build-arg" "ALT_TAG=${ALT_TAG}"
+        "--build-arg" "BASE_IMAGE=${BASE_IMAGE:-}"
+        "--build-arg" "IMG_FLAVOR=${IMG_FLAVOR:-}"
     )
 
     BUILD_LABELS=(
@@ -38,8 +38,8 @@ prep_metadata() {
         "${COMMIT_SHA:0:7}"
         "${MAJOR_VERSION}.${DATESTAMP}"
         "${MAJOR_VERSION}.${DATETIMESTAMP}"
-        "${ALT_TAG}"
-        "${ALT_TAG}.${DATETIMESTAMP}"
+        "${IMG_FLAVOR:-}"
+        "${IMG_FLAVOR:-}.${DATETIMESTAMP}"
     )
 }
 
@@ -47,13 +47,14 @@ sect_border() {
     symmetric_heading "#" "#" "100" "blue" | tr ' ' '#'
 }
 
-# SC2154 - variable is referenced but not assigned.
-# shellcheck disable=SC2154
 build_image() {
     local log_dir="${SCRIPT_DIR}/.log/${IMAGE_NAME}"
     local log_file="${log_dir}/${IMAGE_NAME}.${DATETIMESTAMP}.log"
     local sec_type="${SEC_TYPE:-"id=sbmok_priv,src=${SBMOK_KEY},type=file"}"
     local tag build_tags=()
+
+    [[ -n "${BASE_IMAGE:-}" ]] || die "Missing BASE_IMAGE"
+    [[ -n "${IMG_FLAVOR:-}" ]] || die "Missing IMG_FLAVOR"
 
     for tag in ${BUILD_TAGS}; do
         build_tags+=("--tag" "${IMAGE_NAME}:${tag}")
@@ -77,6 +78,7 @@ build_image() {
                  --dns 9.9.9.9 \
                  --secret "${sec_type}" \
                  --file "Containerfile" \
+                 --target "${IMAGE_NAME}" \
                  "${BUILD_LABELS[@]}" \
                  "${BUILD_ARGS[@]}" \
                  "${build_tags[@]}" \
@@ -132,7 +134,9 @@ chunk_image() {
 push_image() {
     # Always push image without chunked suffix
     local push_image="${IMAGE_NAME/-chunked/}" push_tags="${BUILD_TAGS}" tag
-    digestfile="/tmp/digestfile"
+    digestfile="/tmp/${push_image}-digestfile"
+
+    [[ -n "${IMG_FLAVOR:-}" ]] || die "Missing IMG_FLAVOR"
 
     sect_border
     echo "${green}"  " Pushing       - ${push_image}:${DEFAULT_TAG}${noc}"
@@ -152,8 +156,25 @@ push_image() {
     _cmd_test_timer_end=$(cmd_test_timer)
 
     sect_border
-    echo "${green}"  " Push Done    - ${IMAGE_NAME}:${DEFAULT_TAG}${noc}"
-    echo "${purple}" " Push Time    - ${_cmd_test_timer_end}${noc}"
+    echo "${green}"  " Push Done     - ${IMAGE_NAME}:${DEFAULT_TAG}${noc}"
+    echo "${purple}" " Push Time     - ${_cmd_test_timer_end}${noc}"
+    sect_border
+}
+
+cosign_image() {
+    local digest="$(< "/tmp/${IMAGE_NAME}-digestfile")"
+    [[ -n "$(command -v cosign") ]] || die "Failed, cosign command not found on current system"
+
+    sect_border
+    echo "${green}"  " Signing OCI   - ${IMAGE_NAME}:${DEFAULT_TAG}${noc}"
+    echo "${purple}" " Push Registry - ${PUSH_REGISTRY}${noc}"
+    sect_border
+
+    COSIGN_EXPERIMENTAL=false \
+    cosign sign -y --key env://COSIGN_PRIVATE_KEY "${PUSH_REGISTRY}/${IMAGE_NAME}@${digest}"
+
+    sect_border
+    echo "${green}"  " Signing Done  - ${IMAGE_NAME}:${DEFAULT_TAG}${noc}"
     sect_border
 }
 
@@ -165,15 +186,16 @@ Global Options:
   -h, --help          Show this help message
   -i, --image-name    Set default image name of build
   -b, --base-image    Set base image to build upon
-  -t, --alt-tag       Set an alt tag for image build
+  -f, --img-flavor    Set an alt tag for image build
 
 Commands:
   build               Build the container image using podman
   chunk               Create a chunked OCI image using rpm-ostree
   push                Push the image with tag(s) to the configured registry
+  cosign              Signing container image using Sigstore
 
 Example:
-  $(basename "${0}") build chunk push -i my-image -t main -b quay.io/fedora-ostree-desktops/silverblue
+  $(basename "${0}") build chunk push cosign -i my-image -t main -b quay.io/fedora-ostree-desktops/silverblue
 EOF
 }
 
@@ -232,11 +254,9 @@ main() {
                 [[ -n "${2:-}" ]] || die "Provide image name"
                 IMAGE_NAME="${2}";  shift 2 ;;
             -b|--base-image)
-                [[ -n "${2:-}" ]] || die "Provide base image"
                 BASE_IMAGE="${2}";  shift 2 ;;
-            -t|--alt-tag)
-                [[ -n "${2:-}" ]] || die "Provide alt tag"
-                ALT_TAG="${2}";     shift 2 ;;
+            -f|--img-flavor)
+                IMG_FLAVOR="${2}";     shift 2 ;;
             *)
                 rem_args+=("${1}"); shift   ;;
         esac
